version: 2.1
jobs:
  compile:
   docker:
      - image: nexgang/ubuntu:latest
   steps:
      - add_ssh_keys:
          fingerprints:
          - "eb:4a:8a:96:4e:45:8f:c2:fd:41:f9:16:44:65:50:30"
      - run:
          command: |
            apt update && apt upgrade -y
            apt install -f -y git
            ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
            git clone --depth=1 https://github.com/fredslbn/chime2.git -b main builder_kernel
            cd builder_kernel
            
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
